In [69]:
#Abbiamo una lista di liste: 
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
#Che tipo di struttura dati o matematica potrebbe rappresentare?
#Notare che tutte le liste "interne" sono della stessa dimensione #potrebbe essere una matrice 3x5 (3 colonne e 5 righe)
#Come facciamo per accedere ad un elemento in particolare? #possiamo accedere ad un elemento in particolare 
#trasformando la lista di liste in una series ed accedere ad ogni singola riga tramite indice.
import pandas as pd

In [70]:
my_series = pd.Series (mat, index = list( "abc"))
print (my_series)
my_series ["a"]

a         [0, 1, 2, 3, 4]
b         [5, 6, 7, 8, 9]
c    [10, 11, 12, 13, 14]
dtype: object


[0, 1, 2, 3, 4]

In [72]:
#Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e 
#la variabile .pi la riconoscete?
import math as m
x = int (input ("scegli un numero"))
print ("il seno di x è: " , m.sin(x))
print ("il coseno di x è: " , m.cos(x))
print ("il fattoriale di x è:" , m.factorial(x))
print (".pi indica il pi greco ed il suo valore è", m.pi)

scegli un numero 5


il seno di x è:  -0.9589242746631385
il coseno di x è:  0.28366218546322625
il fattoriale di x è: 120
.pi indica il pi greco ed il suo valore è 3.141592653589793


In [73]:
#Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato?
#Per saperne di più su questa funzione possiamo usare help(math.degrees)
math.degrees (math.pi)
#la funzione math.degrees trasforma i numeri naturali in radianti (gradi)

180.0

In [74]:
#L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
#trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: 
#• qual è stata la vendita massima mensile? E quella minima? 
#• quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? 
#• quali sono le vendite minori di 3000 oggetti?
#•in media quanti oggetti sono stati venduti al mese?
import numpy as np

In [115]:
lst = np.array(lst) #casting
print(lst)

[2000 5500 7200 4320 1280 1900 2500 3900 6410 8150 7100 5350]


In [116]:
print ("la vendita massima mensile è" , lst.max())
print ("la vendita minima mensile è" , lst.min())

la vendita massima mensile è 8150
la vendita minima mensile è 1280


In [117]:
vendite_maggiori_di_5000 = lst > 5000 #creo una maschera booleana
valori5000 = lst[vendite_maggiori_di_5000] #prendo solo i valori per cui la maschera boolenana mi restituisce TRUE
print (valori5000) 
print (len(valori5000)) #conto i valori per cui la maschera boolenana restituisce TRUE

[5500 7200 6410 8150 7100 5350]
6


In [118]:
vendite_minori_di_3000 = lst < 3000
print (lst [vendite_minori_di_3000])
print (lst.mean()) #media delle vendite mensili

[2000 1280 1900 2500]
4634.166666666667


In [119]:
#Consideriamo il seguente dizionario: 
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#Consideriamo ora la seguente Series:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)) 
#Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997] 
#Dunque qual è la differenza tra i due tipi di dato?
#cosa possiamo fare con la series che non possiamo fare con il dizionario?
print (fatturati_dict[2004])
print (fatturati_series[2004]) 
# possiamo accedere ai dati nello stesso modo, ma la differenza tra i due tipi di dato è che i dct sono propri della libreria_std di Python, 
#mentre le series sono proprie di Numpy che è una libreria esterna, inoltre mentre il dict è monodimensionale, la series è multidimensionale.
#con le series possiamo fare un'operazione su tutti gli elementi in un solo passaggio con i dct no
#con la series ho accesso ai dati con la posizione, con il dict accedo ai dati solo tramite chiave perchè è una collection non ordinata

21000
21000


In [120]:
#L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] ) 
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: • con un ciclo for 7 • con il masking
#1) con il masking
stipendi_doppi = stipendi*2
print (stipendi_doppi)
#2) con il ciclo for
for stipendio in stipendi:
    stipendio = stipendi * 2
print (stipendio)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [121]:
#Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi;
lista = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
#gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.
if len (lista) < 3:
    print ("la lista è troppo corta")
elif len (lista) > 3:
    lista.sort(reverse = True)
    print(lista[0:3])

[1000, 900, 800]


In [122]:
#Scrivere un programma che 
#• in input acquisisce una lista di numeri e un numero K 
#• in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
#• se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.
lista = [2, 1000, 350, 7, 28, 49, 678, 0, 89, 412, 5421, 862, 7648]
K = 80
lista_array = np.array(lista)
filtro = lista_array >= K
lista_array_filtrata = lista_array [filtro]
print (lista_array_filtrata) #numeri >= K
lista_array_filtrata.mean() #media dei numeri >= K
if len(lista_array_filtrata) == 0:
    print ("non ci sono numeri maggiori o uguali a 80")
else:
    print ("la media dei numeri >= a K è", lista_array_filtrata.mean())

[1000  350  678   89  412 5421  862 7648]
la media dei numeri >= a K è 2057.5


In [123]:
#Scrivere un programma che, data una lista di numeri, 
#come output stamperà lo stesso numero di asterischi su righe diverse, 
#ottenendo una semplice visualizzazione grafica Esempio, supponendo di avere il seguente input: 
#numeri = [5, 2, 3, 4] L'output sarà: ***** ** *** ****
numeri = [5, 2, 3, 4]
for numero in numeri:
    print ( "*" * numero)


*****
**
***
****


In [124]:
#Abbiamo una lista di codici fiscali: 
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"] 
#• trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla; 
#• inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome.
lista_cf_95 = []
for cf in lista_cf:
    if "95" in cf:           #l'operatore in serve per vedere se una sotto stringa appartiene a una stringa o a una frase
        lista_cf_95.append(cf)
        print (cf, "-", cf[:3], cf[3:6])
print (lista_cf_95)

ABCDEF95G01A123B - ABC DEF
STUVWX95Z04A654E - STU VWX
DEFGHI95J06A987G - DEF GHI
['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [125]:
#Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati 
#dello stesso studente: 
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3] 
#• Stampare a video tutti e soli gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.
for contatore in range(len(edizioni)):
    edizione = edizioni [contatore]
    if edizione == 1:
        studente = studenti [contatore]
        print (studente)

Alex
Faith


In [126]:
#Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro: 
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] 
#cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; 
#il risultato sarà memorizzato in un'altra lista.
prezzi_agg = []
for prezzo in prezzi:
    prezzo_aggiustato = prezzo.replace("€" , "$")
    print(prezzo_aggiustato)
    prezzi_agg.append(prezzo_aggiustato)
print(prezzi_agg)

100 $
200 $
500 $
10 $
50 $
70 $
['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [127]:
#Abbiamo una lista di studenti: 
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 
#vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: 
#selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra. 
#Creiamo due liste per ogni squadra, e alla fine visualizziamole.
squadra_1 = [] #posizioni dispari
squadra_2 = [] #posizioni pari
for studente in range(len(studenti)):
    if studente % 2 == 0:     # posizione pari
        squadra_2.append(studenti[studente])
    else:             # posizione dispari
        squadra_1.append(studenti[studente])
print (squadra_1)
print (squadra_2)


['Bob', 'Dan', 'Faith', 'Henry', 'John']
['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']


In [144]:
#Abbiamo una lista con i guadagni degli ultimi 12 mesi (supponiamo da Gennaio a Dicembre): 
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50] 
#dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, 
#e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti.
import numpy as np
for i, guadagno in enumerate(guadagni):
    if i == 0:
        print("Mese 1:", guadagno, "€ — non ci sono mesi precedenti\n")
        continue
    media = np.mean(guadagni[0:i])
    diff = guadagno - media
    print("Guadagno mese ", i , ": ", guadagno, " €")
    print("Media mesi precedenti: ", media, " €")
    if diff > 0:
        print("il guadagno attuale è maggiore della media dei guadagni dei mesi precedenti\n")
    else:
        print("il guadagno attuale è minore della media dei guadagni dei mesi precedenti\n")


#Esempio di un possibile output: 
#Mese 1: 100 € Mese 2: 90 € (media prec: 100 € - il guadagno attuale è minore) 
#Mese 3: 70 € (media prec: 95 € - il guadagno attuale è minore)

Mese 1: 100 € — non ci sono mesi precedenti

Guadagno mese  1 :  90  €
Media mesi precedenti:  100.0  €
il guadagno attuale è minore della media dei guadagni dei mesi precedenti

Guadagno mese  2 :  70  €
Media mesi precedenti:  95.0  €
il guadagno attuale è minore della media dei guadagni dei mesi precedenti

Guadagno mese  3 :  40  €
Media mesi precedenti:  86.66666666666667  €
il guadagno attuale è minore della media dei guadagni dei mesi precedenti

Guadagno mese  4 :  50  €
Media mesi precedenti:  75.0  €
il guadagno attuale è minore della media dei guadagni dei mesi precedenti

Guadagno mese  5 :  80  €
Media mesi precedenti:  70.0  €
il guadagno attuale è maggiore della media dei guadagni dei mesi precedenti

Guadagno mese  6 :  90  €
Media mesi precedenti:  71.66666666666667  €
il guadagno attuale è maggiore della media dei guadagni dei mesi precedenti

Guadagno mese  7 :  120  €
Media mesi precedenti:  74.28571428571429  €
il guadagno attuale è maggiore della media dei guadagn

In [132]:
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50] 
import numpy as np
np.mean(guadagni[0:4])

np.float64(75.0)

In [134]:
np.mean ([100, 90, 70, 40])

np.float64(75.0)